	FilePath	ExceptionType	ParentType	ParentMethod	TryLine	TryBlock	ParentNodeType	RecoverFlag	Logged	Abort	Default	GetCause	OtherInvocation	Thrown	Return	Continue	FinallyBlock	TryMethods	TryMethodsAndExceptions	TryMethodsBinded	DistinctExceptions	CatchBlock	
'--------------------------------------------------------
NumExceptionType: 2, NumCatchBlock: 3, NumLogged: 2, NumThrown: 0, NumLoggedAndThrown: 0, NumLoggedNotThrown: 2.

'--------------------------------------------------------
Exception Type [System.IO.PathTooLongException]: NumCatchBlock: 2, NumLogged: 2, NumThrown: 0, NumLoggedAndThrown: 0, NumLoggedNotThrown: 2.
ID:1	C:\Users\Administrator\Documents\GitHub\tratch\NTratch\NTratch\test\Class1.cs	System.IO.PathTooLongException	NTratch.test.Person	"Person(string)"	15	try { m1(); // possible exceptions: COMException, and 5 from System method GetFullPath: PathTooLongException, ArgumentException, SecurityException, ArgumentNullException, NotSupportedException m2(); // possible exceptions: AccessViolationException, IOException m2(); // possible exceptions: AccessViolationException, IOException m3(-105); // possible exceptions: NotImplementedException m2(); // possible exceptions: AccessViolationException, IOException m30(); // pe: --- none, it gets swallowed } catch (PathTooLongException ex) { //I'm the catch 22 Console.WriteLine("someone tried to load a path which is too long!" + ex.Message); }	ConstructorDeclaration	'-recoverflag	Console.WriteLine("someone tried to load a path which is too long!" + ex.Message)	'-abort	'-default	'-getcause	'-otherinvocation	'-thrown	'-return	'-continue	'-finallyblock	'-trymethods	{NTratch.test.Person.m1()={System.Runtime.InteropServices.COMException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=1, IsLoop=0, IsThrow=1, DeepestLevelFound=2}, System.ArgumentException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.Security.SecurityException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.ArgumentNullException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.NotSupportedException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.IO.PathTooLongException={HandlerTypeCode=0, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}}, NTratch.test.Person.m2()={System.AccessViolationException={HandlerTypeCode=3, IsXMLSemantic=0, IsXMLSyntax=0, IsLoop=0, IsThrow=1, DeepestLevelFound=1}, System.IO.IOException={HandlerTypeCode=2, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}}, NTratch.test.Person.m3(int)={System.NotImplementedException={HandlerTypeCode=3, IsXMLSemantic=0, IsXMLSyntax=0, IsLoop=0, IsThrow=1, DeepestLevelFound=1}}, NTratch.test.Person.m30()={}}	{NTratch.test.Person.m1()=1, NTratch.test.Person.m2()=1, NTratch.test.Person.m3(int)=1, NTratch.test.Person.m30()=1}	{System.Runtime.InteropServices.COMException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=1, IsLoop=0, IsThrow=1, DeepestLevelFound=2}, System.ArgumentException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.Security.SecurityException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.ArgumentNullException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.NotSupportedException={HandlerTypeCode=3, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.IO.PathTooLongException={HandlerTypeCode=0, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.AccessViolationException={HandlerTypeCode=3, IsXMLSemantic=0, IsXMLSyntax=0, IsLoop=0, IsThrow=1, DeepestLevelFound=1}, System.IO.IOException={HandlerTypeCode=2, IsXMLSemantic=1, IsXMLSyntax=0, IsLoop=0, IsThrow=0, DeepestLevelFound=1}, System.NotImplementedException={HandlerTypeCode=3, IsXMLSemantic=0, IsXMLSyntax=0, IsLoop=0, IsThrow=1, DeepestLevelFound=1}}	catch (PathTooLongException ex) { //I'm the catch 22 Console.WriteLine("someone tried to load a path which is too long!" + ex.Message); }	
ID:2	C:\Users\Administrator\Documents\GitHub\tratch\NTratch\NTratch\test\Class1.cs	System.IO.PathTooLongException	NTratch.test.Person	"m2()"	69	try { //give me the ring! and throw new AccessViolationException(); // I will escape that catch! ha! } catch (PathTooLongException ex) { Console.WriteLine("mama, she called that long file again!"); // I will tell mama if you do that again }	MethodDeclaration	'-recoverflag	Console.WriteLine("mama, she called that long file again!")	'-abort	'-default	'-getcause	'-otherinvocation	'-thrown	'-return	'-continue	'-finallyblock	'-trymethods	{}	{}	{System.AccessViolationException={HandlerTypeCode=3, IsXMLSemantic=0, IsXMLSyntax=0, IsLoop=0, IsThrow=1, DeepestLevelFound=0}}	catch (PathTooLongException ex) { Console.WriteLine("mama, she called that long file again!"); // I will tell mama if you do that again }	


'--------------------------------------------------------
Exception Type [!NO_EXCEPTION_DECLARED!]: NumCatchBlock: 1, NumLogged: 0, NumThrown: 0, NumLoggedAndThrown: 0, NumLoggedNotThrown: 0.
ID:3	C:\Users\Administrator\Documents\GitHub\tratch\NTratch\NTratch\test\Class1.cs	!NO_EXCEPTION_DECLARED!	NTratch.test.Person	"m30()"	57	try { //give me the ring! and throw new DivideByZeroException(); } catch { // don't tell mama anything }	MethodDeclaration	'-recoverflag	'-logged	'-abort	'-default	'-getcause	'-otherinvocation	'-thrown	'-return	'-continue	'-finallyblock	'-trymethods	{}	{}	{System.DivideByZeroException={HandlerTypeCode=-9, IsXMLSemantic=0, IsXMLSyntax=0, IsLoop=0, IsThrow=1, DeepestLevelFound=0}}	catch { // don't tell mama anything }	


'------------------------ Summary -------------------------
Exception Type	NumCatch	NumLogged	NumThrown	NumLoggedAndThrown	NumLoggedNotThrown
System.IO.PathTooLongException	2	2	0	0	2
!NO_EXCEPTION_DECLARED!	1	0	0	0	0
